# 파일 이름을 spring.application.name으로 설정해야 한다.
# 그러므로 이 파일은 product-service에만 적용된다.
# product-service.yml — spring.application.name=product-service 인 서비스에게만 배달된다.
server:
  port: 8081

spring:
  # 서비스마다 자기만의 DB를 갖는다 (Database per Service)
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

product:
  banner:
    message: "쏘양이마켓의 겨울 세일 - 전 상품 10% 할인!"